version: '3.9'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka/
    depends_on:
      - eureka-service

networks:
  app-network:
    driver: bridge
