version: '3.9'

services:
  eureka-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - bank-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  bank-service:
    driver: bridge
