services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USER}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - bank-service
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - bank-service
    restart: unless-stopped

  app:
    container_name: bank-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - bank-service
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  bank-service:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
