server:
  port: 9000
spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**
          filters:
            - AuthenticationFilter

        - id: manager-service
          uri: http://localhost:8081
          predicates:
            - Path=/managers/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: http://localhost:8084
          predicates:
              - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka