server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: ${KET_STORE_PASSWORD}
    key-store-type: JKS
    key-alias: mykey
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    banner-mode: off
  application:
    name: bank-service
  datasource:
    username: ${SPRING_DATASOURCE_USER}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
  driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

