version: '3.9'

services:
  manager-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manager-service
    ports:
      - "8081:8081"
    networks:
      - bank-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka/
    depends_on:
      - auth-service

networks:
  bank-service:
    driver: bridge
