server:
  port: 8761
spring:
  application:
    name: eureka-service
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level.com.netflix.eureka: off
  level.com.netflix.discovery: off
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"